name = "NonconvexUtils"
uuid = "c48e48a2-1f5e-44ff-8799-c8e168d11d1b"
authors = ["Mohamed Tarek <mohamed82008@gmail.com> and contributors"]
version = "0.1.1"

[deps]
AbstractDifferentiation = "c29ec348-61ec-40c8-8164-b8c60e9d9f3d"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
NonconvexCore = "035190e5-69f1-488f-aaab-becca2889735"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
AbstractDifferentiation = "0.4"
ChainRulesCore = "1"
ForwardDiff = "0.10"
IterativeSolvers = "0.8, 0.9"
LinearMaps = "3"
MacroTools = "0.5"
NonconvexCore = "1"
Zygote = "0.5, 0.6"
julia = "1"

[extras]
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"

[targets]
test = ["NamedTupleTools", "NLsolve", "ReverseDiff", "SparseArrays", "StableRNGs", "Test", "Tracker"]
