name = "NonconvexUtils"
uuid = "c48e48a2-1f5e-44ff-8799-c8e168d11d1b"
authors = ["Mohamed Tarek <mohamed82008@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AbstractDifferentiation = "c29ec348-61ec-40c8-8164-b8c60e9d9f3d"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
AbstractDifferentiation = "0.4"
ChainRulesCore = "1"
ForwardDiff = "0.10"
julia = "1"

[extras]
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["ReverseDiff", "Test", "Tracker", "Zygote"]
